---
networks:
  proxy:
    driver: bridge
    external: true

services:
  mysqldb_master:
    image: ${DOCKER_REGISTRY:?error}/${DOCKER_IMAGE:?error}:${DOCKER_IMAGE_TAG:?error}
    restart: unless-stopped
    ports:
      - "${DATABASE_DB_PORT:-3306}:3306"
    environment:
      - TZ=${DATABASE_TIMEZONE:?error}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?error}
      - MYSQL_USER=${MYSQL_USER:?error}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?error}
      - MYSQL_DATABASE=${MYSQL_DATABASE:?error}
    volumes:
      - ${DATABASE_CONFIG_DIR:?error}/development:/etc/mysql/conf.d:ro
      - ${DATABASE_DATA_DIR:?error}/development_db:/var/lib/mysql:rw,cache
    networks:
      - proxy
    ulimits:
      nproc: 65535
      nofile:
        soft: 100000
        hard: 200000
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 15s
      timeout: 5s
      retries: 6
