version: "2.1"

networks:
  proxy:
    driver: bridge
    external: true
  secure:
    driver: bridge
    external: true

services:
  mysqldb-master:
    image: ${DOCKER_REGISTRY?}/${DOCKER_NAMESPACE?}/${DOCKER_IMAGE?}:${DOCKER_IMAGE_TAG?}
    ports:
      - "${DATABASE_DB_PORT}:3306"
    networks:
      - proxy
      - secure
    volumes:
      - ${DATABASE_CONFIG_DIR}/app_custom.cnf:/opt/bitnami/mysql/conf/app_custom.cnf:ro
      - ${DATABASE_DATA_DIR}/db_master:/bitnami/mysql/data
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=${DATABASE_REPLICATION_USER}
      - MYSQL_REPLICATION_PASSWORD=${DATABASE_REPLICATION_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_DATABASE_NAME}
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mysql/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6

  mysqldb-slave:
    image: ${DOCKER_NAMESPACE}/${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}
    ports:
      - "3306"
    networks:
      - secure
    depends_on:
      - mysqldb-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=${DATABASE_REPLICATION_USER}
      - MYSQL_REPLICATION_PASSWORD=${DATABASE_REPLICATION_PASSWORD}
      - MYSQL_MASTER_HOST=mysqldb-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mysql/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6
